# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1212661539);
user_pref("app.update.lastUpdateTime.background-update-timer", 1212661538);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1212661538);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1212661539);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1212661539);
user_pref("browser.migration.version", 1);
user_pref("browser.places.createdSmartBookmarks", false);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.startup.homepage", "file:///root/xpud.html");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.0.1");
user_pref("browser.tabs.forceHide", false);
user_pref("capability.principal.codebase.p0.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p0.id", "file://");
user_pref("capability.principal.codebase.p0.subjectName", "");
user_pref("extensions.enabledItems", "inspector@mozilla.org:2.0.0,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.1");
user_pref("extensions.lastAppVersion", "3.0.1");
user_pref("extensions.update.notifyUser", false);
user_pref("font.language.group", "zh-TW");
user_pref("font.name.monospace.zh-TW", "DejaVu Sans Mono");
user_pref("font.name.sans-serif.zh-TW", "DejaVu Sans");
user_pref("font.name.serif.zh-TW", "AR PL ShanHeiSun Uni");
user_pref("intl.charset.default", "Big5");
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1219284963);
