pref("extensions.{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}.description", "chrome://flashgot/locale/about.properties");
pref("flashgot.GetRight.autostart",false);
pref("flashgot.GetRight.old",false);
pref("flashgot.GetRight.quick",true);
pref("flashgot.LeechGet.httpLog",false);
pref("flashgot.Net_Transport.encode",false);
pref("flashgot.altClick",true);
pref("flashgot.autoReferrer",true);
pref("flashgot.autoStart",true);
pref("flashgot.bgProcessing",true);
pref("flashgot.bypassCombo",true);
pref("flashgot.fakeReferrer","");
pref("flashgot.hide-autotest",true);
pref("flashgot.hideDisabledCmds",true);
pref("flashgot.includeImages",false);
pref("flashgot.interceptAll",false);
pref("flashgot.logEnabled",true);
pref("flashgot.omitCookies",false);
pref("flashgot.hide-icons",false);
pref("flashgot.nested-menu",false);
pref("flashgot.hide-tabs",true);
pref("flashgot.detect.auto",true);
pref("flashgot.Downloader_4_X.quiet",false);
pref("flashgot.extfilter",false);
pref("flashgot.httpauth",false);
pref("flashgot.multiQuiet", false);
pref("flashgot.metalink", true);
pref("flashgot.rsPremium", false);
pref("flashgot.firstRunRedirection", true);


