#!/bin/sh
# /etc/init.d/pudata: save/load data for PUD GNU/Linux

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

case "$1" in
    start)
        sudo pudata load
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
	sudo pudata save
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
