#!/bin/sh
set -e
# Automatically added by dh_pycentral
#if which pycentral >/dev/null 2>&1 && pycentral --help 2>/dev/null | grep -q pkgprepare; then
#	if grep -qs '^python-apt$' /var/lib/pycentral/delayed-pkgs; then
#		pycentral pkginstall python-apt
#		sed -i '/^python-apt$/d' /var/lib/pycentral/delayed-pkgs
#	else
#		pycentral bccompile python-apt
#	fi
#else
#	pycentral pkginstall python-apt
#fi
# End automatically added section
