# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.background-update-timer", 1216224066);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1216224066);
user_pref("browser.places.importDefaults", false);
user_pref("capability.principal.codebase.p0.granted", "UniversalXPConnect");
user_pref("capability.principal.codebase.p0.id", "file://");
user_pref("capability.principal.codebase.p0.subjectName", "");
user_pref("extensions.enabledItems", "");
user_pref("extensions.lastAppVersion", "0.8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("print.printer_PostScript/default.print_bgcolor", false);
user_pref("print.printer_PostScript/default.print_bgimages", false);
user_pref("print.printer_PostScript/default.print_colorspace", "default");
user_pref("print.printer_PostScript/default.print_command", "lpr ${MOZ_PRINTER_NAME:+-P\"$MOZ_PRINTER_NAME\"}");
user_pref("print.printer_PostScript/default.print_downloadfonts", false);
user_pref("print.printer_PostScript/default.print_edge_bottom", 0);
user_pref("print.printer_PostScript/default.print_edge_left", 0);
user_pref("print.printer_PostScript/default.print_edge_right", 0);
user_pref("print.printer_PostScript/default.print_edge_top", 0);
user_pref("print.printer_PostScript/default.print_evenpages", true);
user_pref("print.printer_PostScript/default.print_footercenter", "");
user_pref("print.printer_PostScript/default.print_footerleft", "&PT");
user_pref("print.printer_PostScript/default.print_footerright", "&D");
user_pref("print.printer_PostScript/default.print_headercenter", "");
user_pref("print.printer_PostScript/default.print_headerleft", "&T");
user_pref("print.printer_PostScript/default.print_headerright", "&U");
user_pref("print.printer_PostScript/default.print_in_color", true);
user_pref("print.printer_PostScript/default.print_margin_bottom", "0.500000012107193");
user_pref("print.printer_PostScript/default.print_margin_left", "0.500000012107193");
user_pref("print.printer_PostScript/default.print_margin_right", "0.500000012107193");
user_pref("print.printer_PostScript/default.print_margin_top", "0.500000012107193");
user_pref("print.printer_PostScript/default.print_oddpages", true);
user_pref("print.printer_PostScript/default.print_orientation", 0);
user_pref("print.printer_PostScript/default.print_pagedelay", 500);
user_pref("print.printer_PostScript/default.print_paper_data", 0);
user_pref("print.printer_PostScript/default.print_paper_height", "279.40");
user_pref("print.printer_PostScript/default.print_paper_name", "na_letter");
user_pref("print.printer_PostScript/default.print_paper_size_type", 1);
user_pref("print.printer_PostScript/default.print_paper_size_unit", 1);
user_pref("print.printer_PostScript/default.print_paper_width", "215.90");
user_pref("print.printer_PostScript/default.print_plex_name", "default");
user_pref("print.printer_PostScript/default.print_resolution_name", "default");
user_pref("print.printer_PostScript/default.print_reversed", false);
user_pref("print.printer_PostScript/default.print_scaling", "  1.00");
user_pref("print.printer_PostScript/default.print_shrink_to_fit", true);
user_pref("print.printer_PostScript/default.print_to_file", false);
user_pref("print.printer_PostScript/default.print_to_filename", "/root/mozilla.ps");
user_pref("print.printer_PostScript/default.print_unwriteable_margin_bottom", 56);
user_pref("print.printer_PostScript/default.print_unwriteable_margin_left", 25);
user_pref("print.printer_PostScript/default.print_unwriteable_margin_right", 25);
user_pref("print.printer_PostScript/default.print_unwriteable_margin_top", 25);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_colorspace", false);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_downloadfonts", false);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_jobtitle", false);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_num_copies", true);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_orientation", true);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_paper_size", true);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_plex", false);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_printincolor", true);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_resolution", false);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_spoolercommand", true);
user_pref("print.tmp.printerfeatures.PostScript/default.colorspace.0.name", "default");
user_pref("print.tmp.printerfeatures.PostScript/default.colorspace.count", 1);
user_pref("print.tmp.printerfeatures.PostScript/default.has_special_printerfeatures", true);
user_pref("print.tmp.printerfeatures.PostScript/default.orientation.0.name", "portrait");
user_pref("print.tmp.printerfeatures.PostScript/default.orientation.1.name", "landscape");
user_pref("print.tmp.printerfeatures.PostScript/default.orientation.count", 2);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.0.height_mm", 210);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.0.is_inch", false);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.0.name", "A5");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.0.width_mm", 148);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.1.height_mm", 297);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.1.is_inch", false);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.1.name", "A4");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.1.width_mm", 210);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.2.height_mm", 420);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.2.is_inch", false);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.2.name", "A3");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.2.width_mm", 297);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.3.height_mm", 279);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.3.is_inch", true);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.3.name", "Letter");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.3.width_mm", 215);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.4.height_mm", 355);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.4.is_inch", true);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.4.name", "Legal");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.4.width_mm", 215);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.5.height_mm", 431);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.5.is_inch", true);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.5.name", "Tabloid");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.5.width_mm", 279);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.6.height_mm", 254);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.6.is_inch", true);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.6.name", "Executive");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.6.width_mm", 190);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.count", 7);
user_pref("print.tmp.printerfeatures.PostScript/default.plex.0.name", "default");
user_pref("print.tmp.printerfeatures.PostScript/default.plex.count", 1);
user_pref("print.tmp.printerfeatures.PostScript/default.resolution.0.name", "default");
user_pref("print.tmp.printerfeatures.PostScript/default.resolution.count", 1);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_colorspace_change", false);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_downloadfonts_change", false);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_jobtitle_change", false);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_orientation_change", true);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_paper_size_change", true);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_plex_change", false);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_printincolor_change", true);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_resolution_change", false);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_spoolercommand_change", true);
