# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("allinonegest.autoscrollCursor", false);
user_pref("allinonegest.autoscrollNoMarker", false);
user_pref("allinonegest.autoscrollRate", 0);
user_pref("allinonegest.autoscrolling2", true);
user_pref("allinonegest.autoscrollpref", 0);
user_pref("allinonegest.dragAlaAcrobat", false);
user_pref("allinonegest.evenOnLink", false);
user_pref("allinonegest.focusMode", 0);
user_pref("allinonegest.functionString", "0|1|2|3|4|71|76|9|54|59|10|12|11|82|47|13|52|69|18|17|79|35|57|58|6|61|7|26|14|15|60|34|16|5|39|40|37|38|8|45|30|31|32|27|28|41|80|72|73|74|29|56|43|19|20|21|55|22|62|23|24|25|33|66|36|42|64|65|67|70|75|44|83|48|49|50|51|53|68|46|63|77|81|84|85|78|86|87");
user_pref("allinonegest.gestureString", "L|R|UD|UDU|LU||||||DUD|UL|UR||LR|RLDUR|RL||DR|RLR||+RUL|||||DU|RUDR|RU|DL||+RU|RDLU|DURD|U|D|||ULU|||||RULD|LURD||||||LDUL|LUDL|LDUR|URD|LDRDL|LDR||RDU||RUD|URDR|DRDLU||||||||||||||||||DRD||||||||");
user_pref("allinonegest.gestureTrails", true);
user_pref("allinonegest.goUpInNewTab", false);
user_pref("allinonegest.leftDefault", false);
user_pref("allinonegest.mouse", true);
user_pref("allinonegest.mouse2buttons", false);
user_pref("allinonegest.mousebuttonpref", 2);
user_pref("allinonegest.neverWarnOnCloseOtherTabs", false);
user_pref("allinonegest.nextsString", "next|>");
user_pref("allinonegest.noAltGest", true);
user_pref("allinonegest.noHorizScroll", false);
user_pref("allinonegest.openInCurrTab", false);
user_pref("allinonegest.panning", false);
user_pref("allinonegest.prevsString", "prev|<");
user_pref("allinonegest.reverseScrolling", false);
user_pref("allinonegest.rockerString", "0|1|73|72");
user_pref("allinonegest.rockertypepref", 0);
user_pref("allinonegest.rocking", true);
user_pref("allinonegest.shiftForTitle", true);
user_pref("allinonegest.showLinkTooltip", true);
user_pref("allinonegest.singleWindow", false);
user_pref("allinonegest.tabBar", true);
user_pref("allinonegest.tabRocker", false);
user_pref("allinonegest.titleDelay", 2);
user_pref("allinonegest.titleDuration", 3);
user_pref("allinonegest.trailColor", "#009900");
user_pref("allinonegest.trailSize", 6);
user_pref("allinonegest.trustAutoSelect", false);
user_pref("allinonegest.wheelHistoryIfCw", true);
user_pref("allinonegest.wheelScrollEnhancer", true);
user_pref("allinonegest.wheelpref2", 3);
user_pref("allinonegest.wheelscrolling", true);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1149568126);
user_pref("app.update.lastUpdateTime.background-update-timer", 1149568126);
user_pref("browser.download.manager.closeWhenDone", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.link.open_newwindow", 3);
user_pref("browser.link.open_newwindow.restriction", 0);
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.startup.homepage", "file:///usr/share/ubuntu-artwork/home/index.html");
user_pref("browser.tabs.loadFolderAndReplace", false);
user_pref("extensions.lastAppVersion", "1.5.0.5");
user_pref("extensions.tabmix.dblClickTab", 2);
user_pref("extensions.tabmix.focusTab", 4);
user_pref("extensions.tabmix.hideTabBarButton", true);
user_pref("extensions.tabmix.italicUnread", false);
user_pref("extensions.tabmix.linkTarget", false);
user_pref("extensions.tabmix.newTabButton", false);
user_pref("extensions.tabmix.openTabNext", true);
user_pref("extensions.tabmix.opentabfor.bookmarks", true);
user_pref("extensions.tabmix.opentabfor.search", true);
user_pref("extensions.tabmix.selected_sub_tab1", 3);
user_pref("extensions.tabmix.selected_sub_tab3", 1);
user_pref("extensions.tabmix.selected_sub_tab5", 1);
user_pref("extensions.tabmix.selected_tab", 2);
user_pref("extensions.tabmix.sessions.onStart", 0);
user_pref("extensions.tabmix.sessions.version", "0.1");
user_pref("extensions.tabmix.tabXMode", 0);
user_pref("extensions.tabmix.undoCloseCache", 10);
user_pref("font.default.x-western", "sans-serif");
user_pref("font.language.group", "zh-TW");
user_pref("font.name.monospace.x-western", "monospace");
user_pref("font.name.monospace.zh-TW", "DejaVu Sans Mono");
user_pref("font.name.sans-serif.x-western", "sans-serif");
user_pref("font.name.sans-serif.zh-TW", "DejaVu Sans");
user_pref("font.name.serif.x-western", "serif");
user_pref("font.name.serif.zh-TW", "DejaVu Serif");
user_pref("general.skins.selectedSkin", "Greycurve");
user_pref("gspace.attachmentsize", "14000000");
user_pref("gspace.harmfulext", ".exe,.dll,.zip,.txt,.vb");
user_pref("gspace.previewext", ".jpg,.bmp");
user_pref("gspace.toolbaricon", "no");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.protocol-handler.app.ed2k", "/usr/bin/ed2k.amule");
user_pref("network.protocol-handler.app.opt-get", "/usr/local/bin/remote-opt-get");
user_pref("network.protocol-handler.external.ed2k", true);
user_pref("network.protocol-handler.external.opt-get", true);
user_pref("network.protocol-handler.warn-external.ed2k", false);
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_submit_insecure", false);
user_pref("tongwentang.autoconvert.chineseCharset", "traditional");
user_pref("tongwentang.phrase.outsideTablePath", "");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
