#!/bin/sh
# /etc/init.d/pudding: customize PUD GNU/Linux

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

if [ -f /cdrom/pudding.sh ]; then
    . /cdrom/pudding.sh
fi

for x in $(cat /proc/cmdline); do
	case $x in
	pudding=*)
		pudding=${x#pudding=}
		;;
	esac
done

if [ -f "$pudding" ]; then
    . $pudding
fi

exit 0
